@startuml

!import Entities

package "Data Tables" {
    class Kids DATA_TABLE {
        +Id : GUID
        +Name : string
    }
    class Parents DATA_TABLE {
        +Id : GUID
        +Name : string
    }
    class Charts DATA_TABLE {
        +Id : GUID
        +DateRange : Date
    }
    class Tasks DATA_TABLE {
        +Id : GUID
        +Name : string
        +Description : string
        +Score : integer
    }
    package "Linking Tables" {
        class Parent_Child_Linker LINK_TABLE {
            +ChildId: GUID
            +ParentId : GUID
        }
        class Charts_Tasks_Linker LINK_TABLE {
            +TaskId: GUID
            +ChartId: GUID
        }
        class Charts_Tasks_Linker LINK_TABLE {
            +TaskId: GUID
            +ChartId: GUID
        }
        class Charts_Kids_Linker LINK_TABLE {
            +ChildId: GUID
            +ChartId: GUID
        }
    }
}

package "Domain Entities" {
	class Child ENTITY
	class Parent ENTITY
	class Chart ENTITY
	class Task ENTITY

	Child "1" -u-{ "n" Kids 
	Parent "1" -u-{ "n" Parents
	Chart "1" -u-{ "n" Charts
	Task "1" -u-{ "n" Tasks
}

package "Stored procedures" {
	class GetChildrenByParentId PROCEDURE {
		+ParentId
	}

	class GetTasksForChildId PROCEDURE {
		+ChildId
	}

	Parent_Child_Linker #-u- GetChildrenByParentId
	'GetChildrenByParentId -d-{ Child

	Charts_Kids_Linker #-u- GetTasksForChildId
	Charts_Tasks_Linker #-u- GetTasksForChildId
	'GetTasksForChildId -d-{ Task

}

Charts_Tasks_Linker -d-> Charts
Charts_Tasks_Linker -d-> Tasks

Parent_Child_Linker -d-> Kids
Parent_Child_Linker -d-> Parents

Charts_Kids_Linker -d-> Kids
Charts_Kids_Linker -d-> Charts

@enduml